### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jranma** [Lvl4Sword/PyBitmessage-CLI#8]
Hello, 
For some reason, client is not working on my debian 

root@saturne:~/PyBitmessage/src# ./bitmessagecli.py
Traceback (most recent call last):
  File "./bitmessagecli.py", line 1839, in <module>
    Bitmessage().main()
  File "./bitmessagecli.py", line 1824, in main
    self.unread_message_info()
  File "./bitmessagecli.py", line 1490, in unread_message_info
    inbox_messages = json.loads(self.api.getAllInboxMessages())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

cheers

**Comment by jranma** [comment]
ok, managed to get it running. 

Another error: 
Enter your subject
> hello

Enter your message.
> message

Would you like to add an attachment, (Y)/(n)
> n
API Error 0015: The length of ackData should be 32 bytes (encoded in hex thus 64 characters).

Type (h)elp for a list of commands.

(using protocol 0.6.3.2)
cheers, Julien

**Comment by Lvl4Sword** [comment]
Are you still experiencing this with [latest Bitmessage](https://github.com/Bitmessage/PyBitmessage/tree/v0.6/src)?
